server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: borrow
          uri: http://localhost:8082
          predicates:
            - Path=/borrows/**, 
        - id: return
          uri: http://localhost:8083
          predicates:
            - Path=/returns/**, 
        - id: mypage
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: book
          uri: http://localhost:8085
          predicates:
            - Path=/books/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: borrow
          uri: http://borrow:8080
          predicates:
            - Path=/borrows/**, 
        - id: return
          uri: http://return:8080
          predicates:
            - Path=/returns/**, 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path=, 
        - id: book
          uri: http://book:8080
          predicates:
            - Path=/books/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
